/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "ap-south-1",
  "aws_appsync_graphqlEndpoint": "https://tlvfpvlpdfawzpkgwpyshpu57y.appsync-api.ap-south-1.amazonaws.com/graphql",
  "aws_appsync_region": "ap-south-1",
  "aws_appsync_authenticationType": "API_KEY",
  "aws_appsync_apiKey": "da2-x24d75xw4bffvnizzo6ldyrdy4",
  "aws_cloud_logic_custom": [
    {
      "name": "AdminQueries",
      "endpoint": "https://ii94ewue03.execute-api.ap-south-1.amazonaws.com/dev",
      "region": "ap-south-1"
    }
  ],
  "aws_cognito_identity_pool_id": "ap-south-1:5fb37f5b-2965-404c-b1d4-b109449527f8",
  "aws_cognito_region": "ap-south-1",
  "aws_user_pools_id": "ap-south-1_8rYLQOxFD",
  "aws_user_pools_web_client_id": "7kaf4l9n0qkr0m0i2q3bjucdgv",
  "oauth": {},
  "aws_user_files_s3_bucket": "librarystorage122946-dev",
  "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
